const waterObjects = [
    {
        "Post_Name": "р. Горинь, 478 км, м. Славута, зона впливу ХАЕС",
        "Riverbas_Name": "Дніпро",
        "WaterLab_Name": "Лабораторія моніторингу вод та ґрунтів РОВР у Хмельницькій області",
        "Latitude": "50,282019",
        "Longitude": "26,846494",
        "Controle_Date": "09.10.2018",
        "Azot_Value": "",
        "Azot_Norm": "",
        "Azot_Excess": "",
        "BSK5_Value": "3,38",
        "BSK5_Norm": "3",
        "BSK5_Excess": "1,13",
        "Zavisli_Value": "16",
        "Zavisli_Norm": "15",
        "Zavisli_Excess": "1,07",
        "Kisen_Value": "8,36",
        "Kisen_Norm": "4",
        "Kisen_Excess": "0,48",
        "Sulfat_Value": "44,78",
        "Sulfat_Norm": "100",
        "Sulfat_Excess": "0,45",
        "Hlorid_Value": "25,76",
        "Hlorid_Norm": "300",
        "Hlorid_Excess": "0,09",
        "Amoniy_Value": "0,393",
        "Amoniy_Norm": "0,5",
        "Amoniy_Excess": "0,79",
        "Nitrat_Value": "1,41",
        "Nitrat_Norm": "40",
        "Nitrat_Excess": "0,04",
        "Nitrit_Value": "0,21",
        "Nitrit_Norm": "0,08",
        "Nitrit_Excess": "2,63",
        "Fosfat_Value": "0,337",
        "Fosfat_Norm": "",
        "Fosfat_Excess": "",
        "Total_Index": "22",
        "Report_ID": 391,
        "IDCard_Monitoring": 49602
    },
    {
        "Post_Name": "р. Случ, 406 км, с.Чернелівка, Красилівського р-ну, питний в/з м. Хмельницький",
        "Riverbas_Name": "Дніпро",
        "WaterLab_Name": "Лабораторія моніторингу вод та ґрунтів РОВР у Хмельницькій області",
        "Latitude": "49,673178",
        "Longitude": "26,825783",
        "Controle_Date": "31.03.2021",
        "Azot_Value": "",
        "Azot_Norm": "",
        "Azot_Excess": "",
        "BSK5_Value": "3,29",
        "BSK5_Norm": "3",
        "BSK5_Excess": "1,1",
        "Zavisli_Value": "17",
        "Zavisli_Norm": "15",
        "Zavisli_Excess": "1,13",
        "Kisen_Value": "10,99",
        "Kisen_Norm": "4",
        "Kisen_Excess": "0,36",
        "Sulfat_Value": "53,84",
        "Sulfat_Norm": "100",
        "Sulfat_Excess": "0,54",
        "Hlorid_Value": "38,99",
        "Hlorid_Norm": "300",
        "Hlorid_Excess": "0,13",
        "Amoniy_Value": "0,396",
        "Amoniy_Norm": "0,5",
        "Amoniy_Excess": "0,79",
        "Nitrat_Value": "11,8",
        "Nitrat_Norm": "40",
        "Nitrat_Excess": "0,3",
        "Nitrit_Value": "0,056",
        "Nitrit_Norm": "0,08",
        "Nitrit_Excess": "0,7",
        "Fosfat_Value": "0,02",
        "Fosfat_Norm": "",
        "Fosfat_Excess": "",
        "Total_Index": "11",
        "Report_ID": 391,
        "IDCard_Monitoring": 49612
    },
    {
        "Post_Name": "р. Хомора, 52 км, м. Полонне, питний в/з міста",
        "Riverbas_Name": "Дніпро",
        "WaterLab_Name": "Лабораторія моніторингу вод та ґрунтів РОВР у Хмельницькій області",
        "Latitude": "50,082869",
        "Longitude": "27,488553",
        "Controle_Date": "27.04.2021",
        "Azot_Value": "",
        "Azot_Norm": "",
        "Azot_Excess": "",
        "BSK5_Value": "1,51",
        "BSK5_Norm": "3",
        "BSK5_Excess": "0,5",
        "Zavisli_Value": "7",
        "Zavisli_Norm": "15",
        "Zavisli_Excess": "0,47",
        "Kisen_Value": "13,75",
        "Kisen_Norm": "4",
        "Kisen_Excess": "0,29",
        "Sulfat_Value": "42,84",
        "Sulfat_Norm": "100",
        "Sulfat_Excess": "0,43",
        "Hlorid_Value": "19,79",
        "Hlorid_Norm": "300",
        "Hlorid_Excess": "0,07",
        "Amoniy_Value": "0,76",
        "Amoniy_Norm": "0,5",
        "Amoniy_Excess": "1,52",
        "Nitrat_Value": "0,93",
        "Nitrat_Norm": "40",
        "Nitrat_Excess": "0,02",
        "Nitrit_Value": "0,064",
        "Nitrit_Norm": "0,08",
        "Nitrit_Excess": "0,8",
        "Fosfat_Value": "0,02",
        "Fosfat_Norm": "",
        "Fosfat_Excess": "",
        "Total_Index": "11",
        "Report_ID": 391,
        "IDCard_Monitoring": 49620
    },
    {
        "Post_Name": "р. Південний Буг, 773 км, смт. Чорний Острів, Мар'янівське вдсх.",
        "Riverbas_Name": "Південний Буг",
        "WaterLab_Name": "Лабораторія моніторингу вод та ґрунтів РОВР у Хмельницькій області",
        "Latitude": "49,508172",
        "Longitude": "26,759347",
        "Controle_Date": "12.12.2018",
        "Azot_Value": "",
        "Azot_Norm": "",
        "Azot_Excess": "",
        "BSK5_Value": "11,1",
        "BSK5_Norm": "3",
        "BSK5_Excess": "3,7",
        "Zavisli_Value": "",
        "Zavisli_Norm": "15",
        "Zavisli_Excess": "",
        "Kisen_Value": "4,7",
        "Kisen_Norm": "4",
        "Kisen_Excess": "0,85",
        "Sulfat_Value": "",
        "Sulfat_Norm": "100",
        "Sulfat_Excess": "",
        "Hlorid_Value": "",
        "Hlorid_Norm": "300",
        "Hlorid_Excess": "",
        "Amoniy_Value": "1,483",
        "Amoniy_Norm": "0,5",
        "Amoniy_Excess": "2,97",
        "Nitrat_Value": "2,68",
        "Nitrat_Norm": "40",
        "Nitrat_Excess": "0,07",
        "Nitrit_Value": "0,053",
        "Nitrit_Norm": "0,08",
        "Nitrit_Excess": "0,66",
        "Fosfat_Value": "0,925",
        "Fosfat_Norm": "",
        "Fosfat_Excess": "",
        "Total_Index": "31",
        "Report_ID": 391,
        "IDCard_Monitoring": 49972
    },
    {
        "Post_Name": "р. Південний Буг, 755 км, м. Хмельницький , Хмельницьке вдсх.",
        "Riverbas_Name": "Південний Буг",
        "WaterLab_Name": "Лабораторія моніторингу вод та ґрунтів РОВР у Хмельницькій області",
        "Latitude": "49,431794",
        "Longitude": "26,978928",
        "Controle_Date": "12.12.2018",
        "Azot_Value": "",
        "Azot_Norm": "",
        "Azot_Excess": "",
        "BSK5_Value": "10,45",
        "BSK5_Norm": "3",
        "BSK5_Excess": "3,48",
        "Zavisli_Value": "",
        "Zavisli_Norm": "15",
        "Zavisli_Excess": "",
        "Kisen_Value": "9,87",
        "Kisen_Norm": "4",
        "Kisen_Excess": "0,41",
        "Sulfat_Value": "",
        "Sulfat_Norm": "100",
        "Sulfat_Excess": "",
        "Hlorid_Value": "",
        "Hlorid_Norm": "300",
        "Hlorid_Excess": "",
        "Amoniy_Value": "0,371",
        "Amoniy_Norm": "0,5",
        "Amoniy_Excess": "0,74",
        "Nitrat_Value": "0,7",
        "Nitrat_Norm": "40",
        "Nitrat_Excess": "0,02",
        "Nitrit_Value": "0,032",
        "Nitrit_Norm": "0,08",
        "Nitrit_Excess": "0,4",
        "Fosfat_Value": "0,07",
        "Fosfat_Norm": "",
        "Fosfat_Excess": "",
        "Total_Index": "31",
        "Report_ID": 391,
        "IDCard_Monitoring": 49974
    },
    {
        "Post_Name": "р. Південний Буг, 744 км, с. Копистин, нижче м.Хмельницький",
        "Riverbas_Name": "Південний Буг",
        "WaterLab_Name": "Лабораторія моніторингу вод та ґрунтів РОВР у Хмельницькій області",
        "Latitude": "49,396789",
        "Longitude": "27,108108",
        "Controle_Date": "12.12.2018",
        "Azot_Value": "",
        "Azot_Norm": "",
        "Azot_Excess": "",
        "BSK5_Value": "10,5",
        "BSK5_Norm": "3",
        "BSK5_Excess": "3,5",
        "Zavisli_Value": "",
        "Zavisli_Norm": "15",
        "Zavisli_Excess": "",
        "Kisen_Value": "6,75",
        "Kisen_Norm": "4",
        "Kisen_Excess": "0,59",
        "Sulfat_Value": "",
        "Sulfat_Norm": "100",
        "Sulfat_Excess": "",
        "Hlorid_Value": "",
        "Hlorid_Norm": "300",
        "Hlorid_Excess": "",
        "Amoniy_Value": "25,767",
        "Amoniy_Norm": "0,5",
        "Amoniy_Excess": "51,53",
        "Nitrat_Value": "2,49",
        "Nitrat_Norm": "40",
        "Nitrat_Excess": "0,06",
        "Nitrit_Value": "0,457",
        "Nitrit_Norm": "0,08",
        "Nitrit_Excess": "5,71",
        "Fosfat_Value": "1,754",
        "Fosfat_Norm": "",
        "Fosfat_Excess": "",
        "Total_Index": "52",
        "Report_ID": 391,
        "IDCard_Monitoring": 49976
    },
    {
        "Post_Name": "р. Південний Буг, 711 км,  смт. Меджибіж, Меджибіжське вдсх.",
        "Riverbas_Name": "Південний Буг",
        "WaterLab_Name": "Лабораторія моніторингу вод та ґрунтів РОВР у Хмельницькій області",
        "Latitude": "49,434092",
        "Longitude": "27,412419",
        "Controle_Date": "12.12.2018",
        "Azot_Value": "",
        "Azot_Norm": "",
        "Azot_Excess": "",
        "BSK5_Value": "6,65",
        "BSK5_Norm": "3",
        "BSK5_Excess": "2,22",
        "Zavisli_Value": "",
        "Zavisli_Norm": "15",
        "Zavisli_Excess": "",
        "Kisen_Value": "3,2",
        "Kisen_Norm": "4",
        "Kisen_Excess": "1,25",
        "Sulfat_Value": "",
        "Sulfat_Norm": "100",
        "Sulfat_Excess": "",
        "Hlorid_Value": "",
        "Hlorid_Norm": "300",
        "Hlorid_Excess": "",
        "Amoniy_Value": "27,837",
        "Amoniy_Norm": "0,5",
        "Amoniy_Excess": "55,67",
        "Nitrat_Value": "2,48",
        "Nitrat_Norm": "40",
        "Nitrat_Excess": "0,06",
        "Nitrit_Value": "0,2",
        "Nitrit_Norm": "0,08",
        "Nitrit_Excess": "2,5",
        "Fosfat_Value": "1,136",
        "Fosfat_Norm": "",
        "Fosfat_Excess": "",
        "Total_Index": "52",
        "Report_ID": 391,
        "IDCard_Monitoring": 49978
    },
    {
        "Post_Name": "р. Південний Буг, 692 км, с. Щедрове, Щедрівське вдсх.",
        "Riverbas_Name": "Південний Буг",
        "WaterLab_Name": "Лабораторія моніторингу вод та ґрунтів РОВР у Хмельницькій області",
        "Latitude": "49,412119",
        "Longitude": "27,629853",
        "Controle_Date": "12.12.2018",
        "Azot_Value": "",
        "Azot_Norm": "",
        "Azot_Excess": "",
        "BSK5_Value": "7,4",
        "BSK5_Norm": "3",
        "BSK5_Excess": "2,47",
        "Zavisli_Value": "",
        "Zavisli_Norm": "15",
        "Zavisli_Excess": "",
        "Kisen_Value": "9,63",
        "Kisen_Norm": "4",
        "Kisen_Excess": "0,42",
        "Sulfat_Value": "",
        "Sulfat_Norm": "100",
        "Sulfat_Excess": "",
        "Hlorid_Value": "",
        "Hlorid_Norm": "300",
        "Hlorid_Excess": "",
        "Amoniy_Value": "1,483",
        "Amoniy_Norm": "0,5",
        "Amoniy_Excess": "2,97",
        "Nitrat_Value": "2,42",
        "Nitrat_Norm": "40",
        "Nitrat_Excess": "0,06",
        "Nitrit_Value": "0,089",
        "Nitrit_Norm": "0,08",
        "Nitrit_Excess": "1,11",
        "Fosfat_Value": "0,509",
        "Fosfat_Norm": "",
        "Fosfat_Excess": "",
        "Total_Index": "22",
        "Report_ID": 391,
        "IDCard_Monitoring": 49980
    }
]